#define OP_READ (0)
#define OP_WRITE (1)
#define OP_C_READ (2)
#define OP_C_WRITE (3)
#define OP_ADD_WRITE (4)
#define OP_ADD (5)
#define OP_SUB (6)
#define OP_MUL (7)
#define OP_DIV (8)
#define OP_AND (9)
#define OP_OR (10)
#define OP_XOR (11)
#define OP_NOT (12)
#define OP_0_EQUALS (13)
#define OP_0_GREATER (14)
#define OP_0_LESS (15)
#define OP_0_SUB (16)
#define OP_1_ADD (17)
#define OP_1_SUB (18)
#define OP_2_MUL (19)
#define OP_2_DIV (20)
#define OP_DUP (21)
#define OP_DROP (22)
#define OP_SWAP (23)
#define OP_ROT (24)
#define OP_OVER (25)
#define OP_PICK (26)
#define OP_SEMICOLON (27)
#define OP_FROM_R (28)
#define OP_TO_R (29)
#define OP_COMMA (30)
#define OP_DOLLAR_BR (31)
#define OP_DOLLAR_0BR (32)
#define OP_DOLLAR_LIT (33)
#ifdef INCLUDE_PRIMITIVE_STATIC
static const char *_primitives[] = { "@","!","c@","c!","+!","+","-","*","/","and","or","xor","not","0=","0>","0<","0-","1+","1-","2*","2/","dup","drop","swap","rot","over","pick",";","r>",">r",",","$br","$0br","$lit"};
#endif
