// Automatically generated
#define OP_Read         (0)
#define OP_Store        (1)
#define OP_CRead        (2)
#define OP_Cstore       (3)
#define OP_Addstore     (4)
#define OP_0Less        (5)
#define OP_0Equals      (6)
#define OP_0Greater     (7)
#define OP_0Sub         (8)
#define OP_Not          (9)
#define OP_1Add         (10)
#define OP_1Sub         (11)
#define OP_2Mul         (12)
#define OP_2Div         (13)
#define OP_Add          (14)
#define OP_Sub          (15)
#define OP_Mul          (16)
#define OP_Div          (17)
#define OP_And          (18)
#define OP_Or           (19)
#define OP_Xor          (20)
#define OP_FromRStack   (21)
#define OP_ToRStack     (22)
#define OP_Dup          (23)
#define OP_Drop         (24)
#define OP_Swap         (25)
#define OP_Rot          (26)
#define OP_Over         (27)
#define OP_Pick         (28)
#define OP_Semi         (29)
#ifdef INCLUDE_PRIMITIVE_TEXT
static const char *_primitives[] = { "@","!","c@","c!","+!","0<","0=","0>","0-","not","1+","1-","2*","2/","+","-","*","/","and","or","xor","r>",">r","dup","drop","swap","rot","over","pick",";"};
#endif